### ISSUE TITLE
Fix Sequin boot in self-hosted

### ISSUE THREAD

**Issue by RTLS** [sequinstream/sequin#648]
```
sequin-1           | ** (File.Error) could not read file "/config/playground.yml": illegal operation on a directory
sequin-1           |     (elixir 1.17.2) lib/file.ex:385: File.read!/1
sequin-1           |     (sequin 0.1.0) lib/sequin/yaml_loader.ex:40: Sequin.YamlLoader.apply!/0
sequin-1           |     nofile:1: (file)
sequin-1           |     (stdlib 6.0.1) erl_eval.erl:904: :erl_eval.do_apply/7
sequin-1           |     (elixir 1.17.2) lib/code.ex:572: Code.validated_eval_string/3
sequin-1 exited with code 1
```

**Comment by RTLS** [comment]
Looks like we have a migration out of order which is causing an invalid schema name error

```
sequin-1           | ** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) schema "sequin_config" does not exist
sequin-1           |     (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
sequin-1           |     (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
sequin-1           |     (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1161: Ecto.Adapters.SQL.execute_ddl/4
sequin-1           |     (ecto_sql 3.11.3) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
sequin-1           |     (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
sequin-1           |     (ecto_sql 3.11.3) lib/ecto/migration/runner.ex:311: Ecto.Migration.Runner.perform_operation/3
sequin-1           |     (stdlib 6.0.1) timer.erl:590: :timer.tc/2
sequin-1 exited with code 1
```

**Comment by RTLS** [comment]
[https://github.com/sequinstream/sequin/commit/f9b6792ee76467fb068111fcd3983d8c52fa3757](https://github.com/sequinstream/sequin/commit/f9b6792ee76467fb068111fcd3983d8c52fa3757)

**Comment by RTLS** [comment]
[https://github.com/sequinstream/sequin/commit/bd2e99228df90d4f17cfc88d921daba1a1deaf1f](https://github.com/sequinstream/sequin/commit/bd2e99228df90d4f17cfc88d921daba1a1deaf1f)
