### ISSUE TITLE
Allow removing a user from an account even if it's their last account

### ISSUE THREAD

**Issue by acco** [sequinstream/sequin#786]
Address this error. We can bump the user into a personal account if that's easiest:

```
** (Postgrex.Error) ERROR P0001 (raise_exception) User must have at least one associated account
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.11.2) lib/ecto/repo/schema.ex:775: Ecto.Repo.Schema.apply/4
    (ecto 3.11.2) lib/ecto/repo/schema.ex:571: anonymous fn/13 in Ecto.Repo.Schema.do_delete/4
    (sequin 0.1.0) lib/sequin_web/live/settings/account_settings_live.ex:140: SequinWeb.Settings.AccountSettingsLive.handle_event/3
```

**Comment by girishramnani** [comment]
So making the account personal should be the best move?
